const product = [
    {
        id: 001,
        name: 'Apples',
        category: 'Fruits',
        price: 1000,
        description: 'Sweet and juicy local apples from Jos Area',
        imageUrl : "./media/apples.jpg",
        rating: 4.5,
        stock: 100,
        location: 'local',
    },
    {
        id: 002,
        name: 'Bananas',
        category: 'Fruits',
        price: 500,
        description: 'Sweet and ripe bananas from Oyo Area',
        imageUrl : "./media/bananas.jpg",
        rating: 4.0,
        stock: 97,
        location: 'local',
    },
    {
        id: 003,
        name: 'Limes',
        category: 'Fruits',
        price: 800,
        description: 'Fruity limes from Benue Area',
        imageUrl : "./media/lime.jpg",
        rating: 4.2,
        stock: 33,
        location: 'local',
    },
    {
        id: 004,
        name: 'Pineapples',
        category: 'Fruits',
        price: 1500,
        description: 'Sweet and juicy pineapples from Lagos Area',
        imageUrl : "./media/pineapples.jpg",
        rating: 4.7,
        stock: 100,
        location: 'local',
    },
    {
        id: 005,
        name: 'Watermelon',
        category: 'Fruits',
        price: 6000,
        description: 'Huge watermelons from Morocco',
        imageUrl : "./media/watermelons.jpg",
        rating: 4.8,
        stock: 23,
        location: 'foreign',
    },
    {
        id: 007,
        name: 'Pawpaw',
        category: 'Fruits',
        price: 2000,
        description: 'Sweet and fat pawpaw from Abuja Area',
        imageUrl : "./media/papayas.jpg",
        rating: 4.4,
        stock: 14,
        location: 'local',
    },
    {
        id: 008,
        name: 'Mangoes',
        category: 'Fruits',
        price: 1000,
        description: 'The best mangoes from Ogun Area',
        imageUrl : "./media/mangos.jpg",
        rating: 4.3,
        stock: 234,
        location: 'local',
    },
    {
        id: 009,
        name: 'Grapes',
        category: 'Fruits',
        price: 5000,
        description: 'White grapes from South Africa',
        imageUrl : "./media/grapes.jpg",
        rating: 4.9,
        stock: 35,
        location: 'foreign',
    },
    {
        id: 006,
        name: 'Strawberries',
        category: 'Fruits',
        price: 3000,
        description: 'Sweet and juicy strawberries from Jos Area',
        imageUrl : "./media/strawberries.jpg",
        rating: 4.7,
        stock: 67,
        location: 'local',
    },
    {
        id: 011,
        name: 'Blueberries',
        category: 'Fruits',
        price: 12000,
        description: 'Tiny blueberries from Poland',
        imageUrl : "./media/blueberries.jpg",
        rating: 4.8,
        stock: 100,
        location: 'foreign',
    },
    {
        id: 012,
        name: 'Avocado',
        category: 'Vegetables',
        price: 5000,
        description: 'Fresh and creamy avocados from Mambilla Area',
        imageUrl : "./media/avocados.jpg",
        rating: 4.6,
        stock: 46,
        location: 'local',
    },
    {
        id: 013,
        name: 'Carrots',
        category: 'Vegetables',
        price: 1000,
        description: 'Sweet and crunchy carrots from Jos Area',
        imageUrl : "./media/carrots.jpg",
        rating: 4.2,
        stock: 231,
        location: 'local',
    },
    {
        id: 014,
        name: 'Broccoli',
        category: 'Vegetables',
        price: 12000,
        description: 'Fresh and green broccoli from Morocco',
        imageUrl : "./media/brocolis.jpg",
        rating: 4.0,
        stock: 97,
        location: 'foreign',
    },
    {
        id: 015,
        name: 'chili Peppers',
        category: 'Vegetables',
        price: 800,
        description: 'Spicy chili peppers from Benue Area',
        imageUrl : "./media/chili.jpg",
        rating: 4.2,
        stock: 33,
        location: 'local',
    },
    {
        id: 016,
        name: 'Sweet corn',
        category: 'Vegetables',
        price: 500,
        description: 'Sweet corn from Oyo Area',
        imageUrl : "./media/corn.jpg",
        rating: 4.7,
        stock: 100,
        location: 'local',
    },
    {
        id: 017,
        name: 'Ginger',
        category: 'Vegetables',
        price: 6000,
        description: 'Fresh ginger from Thailand',
        imageUrl : "./media/ginger.jpg",
        rating: 4.8,
        stock: 23,
        location: 'foreign',
    },
    {
        id: 018,
        name: 'Plantain',
        category: 'Vegetables',
        price: 2000,
        description: 'Big ripe plantain from Abuja Area',
        imageUrl : "./media/plantain.jpg",
        rating: 4.4,
        stock: 14,
        location: 'local',
    },
    {
        id: 019,
        name: 'Sweet Potatoes',
        category: 'Vegetables',
        price: 1000,
        description: 'Sweet potatoes from Ogun Area',
        imageUrl : "./media/swpotato.jpg,
        rating: 4.3,
        stock: 234,
        location: 'local',
    },
    {
        id: 010,
        name: 'tomatoes',
        category: 'Vegetables',
        price: 1000,
        description: 'Fresh tomatoes from Lagos State',
        imageUrl : "./media/tomatoes.jpg",
        rating: 4.9,
        stock: 350,
        location: 'local',
    },
    {
        id: 020,
        name: 'Yam',
        category: 'Vegetables',
        price: 3000,
        description: 'Fat ripe yam from Jos Area',
        imageUrl : "./media/yam.jpg",
        rating: 4.7,
        stock: 67,
        location: 'local',
    },
    
]