export const products = [
    {
        id: 101,
        name: 'Apples',
        category: 'Fruits',
        price: 1000,
        description: 'Sweet and juicy local apples from Jos Area',
        imageUrl : "/apples.jpg",
        rating: 4.5,
        stock: 100,
        location: 'local',
    },
    {
        id: 102,
        name: 'Bananas',
        category: 'Fruits',
        price: 500,
        description: 'Sweet and ripe bananas from Oyo Area',
        imageUrl : "/bananas.jpg",
        rating: 4.0,
        stock: 97,
        location: 'local',
    },
    {
        id: 103,
        name: 'Limes',
        category: 'Fruits',
        price: 800,
        description: 'Fruity limes from Benue Area',
        imageUrl : "/lime.jpg",
        rating: 4.2,
        stock: 33,
        location: 'local',
    },
    {
        id: 104,
        name: 'Pineapples',
        category: 'Fruits',
        price: 1500,
        description: 'Sweet and juicy pineapples from Lagos Area',
        imageUrl : "/pineapples.jpg",
        rating: 4.7,
        stock: 100,
        location: 'local',
    },
    {
        id: 105,
        name: 'Watermelon',
        category: 'Fruits',
        price: 6000,
        description: 'Huge watermelons from Morocco',
        imageUrl : "/watermelons.jpg",
        rating: 4.8,
        stock: 23,
        location: 'foreign',
    },
    {
        id: 107,
        name: 'Pawpaw',
        category: 'Fruits',
        price: 2000,
        description: 'Sweet and fat pawpaw from Abuja Area',
        imageUrl : "/papayas.jpg",
        rating: 4.4,
        stock: 14,
        location: 'local',
    },
    {
        id: 108,
        name: 'Mangoes',
        category: 'Fruits',
        price: 1000,
        description: 'The best mangoes from Ogun Area',
        imageUrl : "/mangos.jpg",
        rating: 4.3,
        stock: 234,
        location: 'local',
    },
    {
        id: 109,
        name: 'Grapes',
        category: 'Fruits',
        price: 5000,
        description: 'White grapes from South Africa',
        imageUrl : "/grapes.jpg",
        rating: 4.9,
        stock: 35,
        location: 'foreign',
    },
    {
        id: 106,
        name: 'Strawberries',
        category: 'Fruits',
        price: 3000,
        description: 'Sweet and juicy strawberries from Jos Area',
        imageUrl : "/strawberries.jpg",
        rating: 4.7,
        stock: 67,
        location: 'local',
    },
    {
        id: 111,
        name: 'Blueberries',
        category: 'Fruits',
        price: 12000,
        description: 'Tiny blueberries from Poland',
        imageUrl : "/blueberries.jpg",
        rating: 4.8,
        stock: 100,
        location: 'foreign',
    },
    {
        id: 112,
        name: 'Avocado',
        category: 'Vegetables',
        price: 5000,
        description: 'Fresh and creamy avocados from Mambilla Area',
        imageUrl : "/avocados.jpg",
        rating: 4.6,
        stock: 46,
        location: 'local',
    },
    {
        id: 113,
        name: 'Carrots',
        category: 'Vegetables',
        price: 1000,
        description: 'Sweet and crunchy carrots from Jos Area',
        imageUrl : "/carrots.jpg",
        rating: 4.2,
        stock: 231,
        location: 'local',
    },
    {
        id: 114,
        name: 'Broccoli',
        category: 'Vegetables',
        price: 12000,
        description: 'Fresh and green broccoli from Morocco',
        imageUrl : "/brocolis.jpg",
        rating: 4.0,
        stock: 97,
        location: 'foreign',
    },
    {
        id: 115,
        name: 'chili Peppers',
        category: 'Vegetables',
        price: 800,
        description: 'Spicy chili peppers from Benue Area',
        imageUrl : "/chili.jpg",
        rating: 4.2,
        stock: 33,
        location: 'local',
    },
    {
        id: 116,
        name: 'Sweet corn',
        category: 'Vegetables',
        price: 500,
        description: 'Sweet corn from Oyo Area',
        imageUrl : "/corn.jpg",
        rating: 4.7,
        stock: 100,
        location: 'local',
    },
    {
        id: 117,
        name: 'Ginger',
        category: 'Vegetables',
        price: 6000,
        description: 'Fresh ginger from Thailand',
        imageUrl : "/ginger.jpg",
        rating: 4.8,
        stock: 23,
        location: 'foreign',
    },
    {
        id: 118,
        name: 'Plantain',
        category: 'Vegetables',
        price: 2000,
        description: 'Big ripe plantain from Abuja Area',
        imageUrl : "/plantain.jpg",
        rating: 4.4,
        stock: 14,
        location: 'local',
    },
    {
        id: 119,
        name: 'Sweet Potatoes',
        category: 'Vegetables',
        price: 1000,
        description: 'Sweet potatoes from Ogun Area',
        imageUrl : "/swpotato.jpg",
        rating: 4.3,
        stock: 234,
        location: 'local',
    },
    {
        id: 110,
        name: 'tomatoes',
        category: 'Vegetables',
        price: 1000,
        description: 'Fresh tomatoes from Lagos State',
        imageUrl : "/tomatoes.jpg",
        rating: 4.9,
        stock: 350,
        location: 'local',
    },
    {
        id: 120,
        name: 'Yam',
        category: 'Vegetables',
        price: 3000,
        description: 'Fat ripe yam from Jos Area',
        imageUrl : "/yam.jpg",
        rating: 4.7,
        stock: 67,
        location: 'local',
    },
    
]